services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432" # 5433 host, 5432 container
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: